const noop = () => {};
export const _ = noop;
export const a = noop;
export const b = noop;
export const c = noop;
export const f = noop;
export const h = noop;
export const i = noop;
export const l = noop;
export const p = noop;